Vagrant.configure("2") do |config| 
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    #Databse vm
    config.vm.define "db01" do |db01|
        db01.vm.box = "eurolinux-vagrant/centos-stream-9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.2"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "1600"
        end 
         db01.vm.provision "shell", path: "mysql.sh" 
    end

    #Memcache vm
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.3"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "1600"
        end
         mc01.vm.provision "shell", path: "memcache.sh" 
    end

    #RabbitmQ vm 
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.4"
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = "1600"
        end
         rmq01.vm.provision "shell", path: "rabbitmq.sh"
    end

    #tomcat vm
    config.vm.define "app01" do |app01|
        app01.vm.box = "eurolinux-vagrant/centos-stream-9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.56.5"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "1600"
        end
    end

    #nginx vm
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.6"
        web01.vm.provider "virtualbox" do|vb|
            vb.memory = "1600"
        end
         web01.vm.provision "shell", path: "nginx.sh" 
    end

    end




